[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.4"

[[override]]
  name = "k8s.io/client-go"
  # revision for tag "kubernetes-1.13.1"
  revision = "8d9ed539ba3134352c586810e749e58df4e94e4f"

[[constraint]]
  name = "github.com/operator-framework/operator-lifecycle-manager"
  version = "v0.10.0"

[prune]
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false

  [[prune.project]]
    name = "k8s.io/gengo"
    non-go = false
